// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDISpMhEWd232REoiWZ8EEiKVn-UmbZlI',
    appId: '1:240759395700:web:a3fa1aa88cce6b2ec88821',
    messagingSenderId: '240759395700',
    projectId: 'crm-evhomes',
    authDomain: 'crm-evhomes.firebaseapp.com',
    storageBucket: 'crm-evhomes.appspot.com',
    measurementId: 'G-81FKSH4VDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVL0Lmm12NHAMHt3-WDh1esBaua_2bAlk',
    appId: '1:240759395700:android:48e3bfb1e6639679c88821',
    messagingSenderId: '240759395700',
    projectId: 'crm-evhomes',
    storageBucket: 'crm-evhomes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdR_VxQHNtEwe5LNNkjyLcTEYQVBQKMvk',
    appId: '1:240759395700:ios:b998f58649d64e33c88821',
    messagingSenderId: '240759395700',
    projectId: 'crm-evhomes',
    storageBucket: 'crm-evhomes.appspot.com',
    iosClientId: '240759395700-dt457302rnbd2gsv6rmv11etvav432ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.evHomesCrmV7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdR_VxQHNtEwe5LNNkjyLcTEYQVBQKMvk',
    appId: '1:240759395700:ios:b998f58649d64e33c88821',
    messagingSenderId: '240759395700',
    projectId: 'crm-evhomes',
    storageBucket: 'crm-evhomes.appspot.com',
    iosClientId: '240759395700-dt457302rnbd2gsv6rmv11etvav432ma.apps.googleusercontent.com',
    iosBundleId: 'com.example.evHomesCrmV7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDISpMhEWd232REoiWZ8EEiKVn-UmbZlI',
    appId: '1:240759395700:web:cd3cf1390c56b607c88821',
    messagingSenderId: '240759395700',
    projectId: 'crm-evhomes',
    authDomain: 'crm-evhomes.firebaseapp.com',
    storageBucket: 'crm-evhomes.appspot.com',
    measurementId: 'G-1TMWSTTMM3',
  );
}
